<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StatusAware\Module' => __DIR__ . '/Module.php',
    'StatusAware\Controller\StatusController' => __DIR__ . '/src/StatusAware/Controller/StatusController.php',
    'StatusAware\StatusManager' => __DIR__ . '/src/StatusAware/Service/StatusManager.php',
    'StatusAware\StatusInterface' => __DIR__ . 'src/StatusAware/ServiceManagerAwareInterface/StatusInterface.php'
);
